branches:
  only:
  - main

language: python
cache: pip
python:
  - '3.8'

services:
  - docker

before_install:
  - bash scripts/preflight.sh || travis_terminate 0

install:
  - cd server
  - pip install -r requirements.txt

script: python3 -m pytest

before-deploy:
  - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
    -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: main

env:
  global:
  - secure: kg3MR8Y+QmfOyyrziDoGjdEZ5YUCXydF0dnil3g8K3mxsshg+ioVIxgYH1V0R7LKpnwlkQ4dGX0FmeYe2CNQz28n2bkGBh+Aofg74jFtWPlElaxOIChaBRrY3JpzoKFnGHGbEqhM4uA7/wqMJ1eAaEZG2Pacwv+3wdZ2O7xzE3WZJoAmIaiLUDi0QXUjCMb9UXf+R0xKy+vyS0vqAzHkWe/HibAthd52JINX4wTma4jyL02aY5374faM9Uzt+lQipN7rvnyklsBdhsQxwiqqFiFQ6Rsui4LbUpbrqvDrTC5Z5j+Ruvn8B34yFDRlA6Crks4UnyKWHc7f5xZ/l7jd/QjFq07a+Tq+mIvEUrUtXq7ttW4c3+Ob4MN8Q7+YLqqbGEe3q3aLRoCy+OP/eieOTN6NjrfrEgsppzG3SQrHv8XOTDgB0rbIp2jQAxS/jKdON5KjjFQ2EFT/E7KWHHR/c8vD9pu5NMDjbHiNeBukbumIDWg1xPNjNxH0Z5Kb+kBPQk+ZMCU/gzV9ZaX0IYZQfULeia4QtMjgWR50Sad+skqbNZT8A+JL5k46fd8GF11XUJ+ZhtC5eEe0TBoMtgblIDo3GQL+GEroIZbsoE6w+9ztOvIbng27ht3t9R11wbvhUMAem34/lS1K7Th1zt58ar92YfGtFjvUew1Gzg0eBKo=
  - secure: Wk0BkZT11XEgzXDE4JjFYqaLsuk1xOZ5JCNi8WArSdggdx0/AJwOR5GrH7nhG8r/tQzM784A/YR6G8swHYk3H98ee+jo9XuFLfTW/0XLvqDGHLrT9DnB6uDS6S3GuqruZq3QxVWmAi9f9QWfkjw0Ax5nArrx+25LcyXpPidqxkVzQtDxoBIFbG523g4KF8r/8ri+XED0uGDRqNU5+4/1Xa/+EqH4CT+tVaeRoZKoZzJUHAVTK1FYxhd85oXibv1JgXWwJKJW9WGj5FzIjoAhKVwqwRM0Hc5BZPsctK7qvbtFZTsoxUdZpxA2ze09lwONIxFEZExwhP0WppYcOyB27rCPbzw69aaAgSkglDgsvQ/NLlUAm3hiIe+P/o6NCr2HvEt+k8fq8qqPe+9q7xI2gFZJyyrqsOtkQZGa+udbz38ywGmGs9CTA1Qkl97DY1qKuNjxjPQo5Q4dhOr3mQxaD3/JK1QGXWXeikrf9nU8LSNc7Db/dDA8weX18D6JCwqEyGgR8HKubhdGnVjPCTSmeQ0Xu44+N0MHRzCL5UjTh6PSJ6I2C7vGyJrSuXYbwiHErFdNjl0BrzA1L1ttXFI8crglzeWE1D6EWvyQKCJ5hJ7S89deDEB51P5EJXLSYd7jFg+HDgvnmwR4iXLJTxk8cCMFTDOd9H2oFRL1dvhJq3Q=
